
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discount_system
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www,
      - /var/www/vendor
    depends_on:
      - db
    env_file: .env
    environment:
      APP_ENV: local
      #APP_DEBUG=true
      DB_CONNECTION: mysql
      DB_PORT: 3306
      DB_HOST: db
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME:  '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
    command: php-fpm
    networks:
      - backend

  web:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - backend

  db:
    mem_limit: 2048m
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    volumes:
    - mysql_data:/var/lib/mysql
    - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - backend
    command: --bind-address=0.0.0.0
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8001:80
    env_file: .env
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
    - backend
  unit-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_tests
    working_dir: /var/www
    depends_on:
      - db
    networks:
      - backend
    command: ["vendor/bin/phpunit"]

volumes:
  mysql_data:
    driver: local

networks:
  backend:
    driver: bridge
